name: XADMaster

on:
  workflow_dispatch:

jobs:
  build:
    name: Build XADMaster and UniversalDetector frameworks
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.3.0
        with:
          submodules: recursive
      - name: Create build directory
        working-directory: ${{github.workspace}}
        run: mkdir build
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@1242409711ff5721add51979e9e11e23ebb7e5a4 # v1.6.0
        with:
          xcode-version: 13.4.1
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: xcodebuild -project "${{github.workspace}}/Vendor/XADMaster/XADMaster.xcodeproj" -scheme XADMaster -configuration Release -sdk macosx -derivedDataPath DerivedData
      - name: Zip framework bundles
        working-directory: ${{github.workspace}}/build/DerivedData/Build/Products/Release/
        run: zip -y -r XADMaster.zip XADMaster.framework UniversalDetector.framework
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: XADMaster.zip
          path: ${{github.workspace}}/build/DerivedData/Build/Products/Release/XADMaster.zip
